language: node_js

node_js:
  - 10.15.3

install:
  - yarn install

script:
  - yarn lint
  - yarn test
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: 
  keep_history: false
  local_dir: build/
  on:
    branch: master
